import org.junit.jupiter.api.Test
import kotlin.test.*

class SolutionTest {

    @Test
    fun BasicTest1() {
        val words1 = arrayOf("great", "acting", "skills")
        val words2 = arrayOf("fine", "drama", "talent")
        val pairs = listOf(
            mutableListOf("great", "fine"),
            mutableListOf("drama", "acting"),
            mutableListOf("skills", "talent")
        )
        assertTrue(Solution().isSentenceSimilarity(words1, words2, pairs))
    }

    @Test
    fun BasicTest2() {
        val words1 = arrayOf("great")
        val words2 = arrayOf("great")
        val pairs = listOf<MutableList<String>>();
        assertTrue(Solution().isSentenceSimilarity(words1, words2, pairs))
    }

    @Test
    fun BasicTest3() {
        val words1 = arrayOf("great")
        val words2 = arrayOf("doubleplus", "good")
        val pairs = listOf<MutableList<String>>();
        assertFalse(Solution().isSentenceSimilarity(words1, words2, pairs))
    }

    @Test
    fun BasicTest4() {
        val words1 = arrayOf(
            "ujcjiroxroclwymggqk",
            "jtctwaf",
            "ulfurrnvyq",
            "jaweoprvmy",
            "qmshgrymnbq",
            "afobhjkk",
            "ttghzzzatlrklrowdcee",
            "wikmwvpumhmcqim",
            "lvwr",
            "qpcioqvgzwbgn",
            "samxstlsegphtpav",
            "cdcamkwgwwlylqfrpgu",
            "thfxpcduq",
            "tvqzkrrcbxxfhxpth",
            "xcagsainqvjiubhhqz",
            "tmagtnhpxxyxyhqbxrve",
            "hjrgoxwqjscnbezqs",
            "esnedvvmujxd",
            "rvp",
            "sjunp",
            "lxz",
            "sezgsulyganlodx",
            "hmbdpbvswnqlctfurzju",
            "hty",
            "oyyoines",
            "tgdkksuosjcsvphibf",
            "ejjanjyualmouscfbs",
            "epnwxogbp",
            "oojxbritzftdkn",
            "euzw",
            "ishnxw",
            "grtxpwzg",
            "anzquvbrmuvvccmnpqc",
            "wnafksi",
            "g",
            "yrymuj",
            "fymwy",
            "jxsj",
            "awgthxflyktg",
            "adronmoqp",
            "wsmcgdhrmrvbwgo",
            "rmhg",
            "zolvvdwx",
            "pjab",
            "pjswidphndhiuam",
            "vmhwrkovbxjzvo",
            "wj",
            "pcbfdtqzcqixxvbcq",
            "rfeyvfnnjdiethd",
            "zpilljxbrckyd",
            "dmyvtjjxyzunkcfcq",
            "uzzzbvmxhwqazsfahbl",
            "dipsedhofmqwxrygpoos",
            "mcspamhx",
            "lagjgiolyawffgmqmhva",
            "nwsij",
            "pynzkxxzqrysxhvpfvx",
            "wxgkuhqwazwzdvzll",
            "mn",
            "hvatvzkbrxwiuazxbkq",
            "nvh",
            "pedwpywglaeokdvbzni",
            "auvqb",
            "ooccshlkcbftm",
            "v",
            "cwtvje",
            "mkexxknaruheiyxnfx",
            "gvgcohqcldhxgkh",
            "lukogbni",
            "ocshmsrfatzuskmd",
            "ejj",
            "p",
            "sstojwkonka",
            "lxo",
            "num",
            "jbd",
            "atiozgwsciqhpier",
            "ldvg",
            "ktyuqcyilcsoxc",
            "dfxmagdbcowigwloehko",
            "lvbg",
            "rbyjeozhqffsv",
            "kepvgxvbyp",
            "qanfai",
            "oob",
            "xlcdgqdacolughoz",
            "futaqwfflrdevipch",
            "a",
            "ivnubphldtiggb",
            "rnzjuwzlxcfmxcrchr",
            "d",
            "c",
            "opcnrtguzrccyfkbtx",
            "vksdvnglooqxqeymtq",
            "kopgduixakgicbdraf",
            "pptwubqvrecgwdddyp",
            "cn",
            "kwcrpizmocx",
            "w",
            "yuxdsva",
            "nuviwitjqvber",
            "agibvpfiepf",
            "swclnguodlvt",
            "alrezbetebbpldhqsqpf",
            "cbnlyetyzbxpxr",
            "gfw",
            "bpkgj",
            "dcqqzadoauy",
            "ktzphyhixqwlrloei",
            "pmicfgtwn",
            "fdbhezob",
            "zjfhmdpdubqpcrljs",
            "xzqyuequpcesbizo",
            "ifkixrjyt",
            "meamxdkbcgkblnaiizz",
            "qwmlb",
            "sqicc",
            "quqfcgtrrdsphf",
            "espuxjbjaydfwnyb",
            "dwytkwou",
            "camg",
            "uatcuscnxeeotaear",
            "mhjbdealnxunxgem",
            "r",
            "eqty",
            "hvrn",
            "bsrijei",
            "p",
            "bfasvganyah",
            "vjsipg",
            "gwwwjuaauoml",
            "ppbelm",
            "kbonuyxzzovxa",
            "lwdonikd",
            "wozexymucaiqqv",
            "prucjqvfzl",
            "xqctom",
            "xhguqsopvslfyidob",
            "lwsfthm",
            "ezfqkf",
            "gfbojeo",
            "nhknajjywhye",
            "xpiq",
            "gpiqjkcsgydkykh",
            "ypdplprqmd",
            "po",
            "kcckxtbieakkibgvt",
            "hwiylrzryjxg",
            "kkbjrjtz",
            "qtvimffxy",
            "ftl",
            "edufjuxyrxtapftzmg",
            "wlixhyufmrrw",
            "vtgedmysfddjipkvnqeh",
            "jjfplanrtlxdugb",
            "d",
            "oikhbtjhdcnw",
            "mpfdtl",
            "ynuyrzahviwyhfu",
            "tkkyrekeqz",
            "pqvoes",
            "qmc",
            "pzibv",
            "ewhyznlamihuqtb",
            "jki",
            "utlqbjnaxw",
            "tvradkk",
            "joutnbrtwfxpyskktopw",
            "eozx",
            "eslwspkg",
            "pkrbseljovsevzdxqds",
            "ebof",
            "smpwxarpolyew",
            "wmnczxakddvmmajg",
            "ftfzekaingyljtxwix",
            "zgmjd",
            "utplueq",
            "vqsrqtmmam",
            "cnnxfszbmzhjew",
            "osqkanxrowymhqwl",
            "q",
            "hqmhdwlyadp",
            "iyqtitjyitbzxgzdcp",
            "xocvjoujdqnk",
            "suymrbbcouzcfjsiog",
            "vvjszhnpfrbu",
            "wljnkhqrzjpawq",
            "qqfgmusddn",
            "yzfemhkmbxqqwuibt",
            "hbg",
            "hfiwvwglvdmt",
            "nooezkhrfimg",
            "glplhqvwq",
            "q",
            "pzl",
            "bnxtrpst",
            "dcclr",
            "oxwbodmqqicwh",
            "wwmehvaqeihwnaoxvted",
            "ykrznlimf",
            "p",
            "jlrfoivnopskfrga",
            "uhxukklyy",
            "yxu",
            "lgahxyipygnumuq",
            "ouhdydmjsmtkzk",
            "rzpmghrpmxwc",
            "qrl",
            "upcdponnfzrhyx",
            "oqjvopvnwmpuhvszgi",
            "zmcdzx",
            "fxq",
            "c",
            "drcaqiswxe",
            "ojejbx",
            "avkbzthupawtc",
            "yoq",
            "qndescuxugfoewxb",
            "gbvxbzbwxnnca",
            "ygypmqkyoqy",
            "qfffmybpekabbuetjxa",
            "nkprvxstnev",
            "nloevyoemx",
            "jsixuxzdoe",
            "ffpl",
            "sqxbownbeqxpp",
            "pimxvbkrm",
            "ac",
            "pkyrmtyfleikoljulq",
            "kdjwqmclz",
            "w",
            "wqhogyxhkhvoqcb",
            "vgfkqntltoarjlganmx",
            "luzztuahacmkpregj",
            "siwxehy",
            "jtpr",
            "mqho",
            "hqwhmosezoeihxkjola",
            "amvjurctaremecyop",
            "sjrxbwhrdr",
            "zxcrrrnxwjvxiapkka",
            "uxzbocbihlehl",
            "ndmd",
            "kgspktobxihjtnvh",
            "cu",
            "zdxaozbcfhzx",
            "ivymhwxtbpn",
            "hfdxagxr",
            "tvqznovxlcd",
            "dnfoqesr",
            "ostudmhji",
            "wdpqetxiqqop",
            "vcxmaonvgk",
            "felorhelowdrljr",
            "lplfuekjxou",
            "gywtqwausjzy",
            "sxsegckaiymklqz",
            "rojfbulrcziyubmp",
            "gnyxzkdntj",
            "zndddcccs",
            "qtijvjcuyyxptz",
            "wuzvkbjrmnbn",
            "tlaxgjnruhyeprmbbrh",
            "tphsnrjyensfcagcmcr",
            "txearitnmzpdteqhy",
            "hy",
            "ezjiiflnqvvwbta",
            "vaedlcrzdtzesbt",
            "z",
            "vhyzahdqqcwhbspb",
            "tuovsrgfdc",
            "ekynynfmqt",
            "zrhzucznpnjcmyfemojo",
            "lmhkbgeouyhk",
            "yvuxjmaczkpxc",
            "ljqpavy",
            "uamwsyvzwhaz",
            "vxeiyliihvup",
            "vhwavpag",
            "fncwcuixzqgwqchif",
            "lgmjp",
            "dprqi",
            "mcdcpiuruvdnmobhz",
            "vxukjn",
            "mfilhjaqdhxembiw",
            "qdxnkbhozg",
            "sbgdj",
            "mtktqttvjmtkfwhgpihq",
            "jbtnvijpphujhm",
            "htogbrzknm",
            "jeibnmylbr",
            "giebneqyyusxfi",
            "auxru",
            "drmiofi",
            "mzntgnxcudlvglbddwpw",
            "gang",
            "znijktfivkcyroaq",
            "qyakiwu",
            "j",
            "jvjkbuyigqbsljduugt",
            "d",
            "utkpnlqzcqjl",
            "cksj",
            "ypwldfgoqn",
            "v",
            "liqvnjiaxxbvc",
            "huwoznvqsqertr",
            "efwvkcqeaojrj",
            "jucvirvlqgyvrxtl",
            "zmujdlwcwmntuk",
            "uywxtad",
            "afbvwzlcyoafbjevfsk",
            "oxbxdowzhfi",
            "duuixykph",
            "e",
            "uxenxwxomhrmf",
            "uhrlrlpqp",
            "tkkchajzgnl",
            "xlmfaylnd",
            "jbxcakghqewctmhbryzf",
            "ebdfskqm",
            "lhhlzzwgmvzqodrr",
            "bbahbwvhoub",
            "aedrqugdgwhzsotx",
            "nvkxsrmgl",
            "ahojsdthxcfqkwhgfwt",
            "qfxstgwhycpqksfiy",
            "bkahzmfylmkglnmogndn",
            "rfbjueoivkmbrhd",
            "cpzg",
            "zlzx",
            "yg",
            "iylqb",
            "ivjdvijlbfjsdbcqqud",
            "mfkhrtmdtrjwnsnuem",
            "msfmwrjqdefkebl",
            "uyyfdpgkxmmhhcaz",
            "zwoimowz",
            "klmjypf",
            "gpiqywwskhomqnupomq",
            "cad",
            "r",
            "ogzggbejqnulxqsafuk",
            "vmsxlobeqawbynzve",
            "s",
            "lfhcl",
            "ialcymrzzveacskteax",
            "rism",
            "pwcrdqebphxnjqmejb",
            "bkuzk",
            "pxzqbh",
            "x",
            "hmtwe",
            "gvnvoatskqrmp",
            "optxlljafpdd",
            "mswttfe",
            "jga",
            "xhbmsxgqlrc",
            "jzihwh",
            "ltlewuxuexccfiht",
            "kievpe",
            "z",
            "xyudyhqlqwacl",
            "fjolgalpaugklukaz",
            "zfseshwgaqwwdoi",
            "p",
            "btbgbjnf",
            "zjkegjnobyfxcji",
            "bktaotdpdceasft",
            "i",
            "dkcox",
            "fzxsmaqo",
            "qy",
            "owvxqegncxiluiuvez",
            "rbzczaesxtuqctemupc",
            "cfadzvzkeo",
            "iwwoqjgwrxdtblweui",
            "ohqosywlniiwi",
            "wtrjssuelmfuk",
            "fmvyu",
            "azpspsumoawvpko",
            "nidlewlbyqjcidduhnxh",
            "cssqdfdcwc",
            "dxxnhbmqnzupnac",
            "usedqbhoxjaawqodbs",
            "eemrmqjvq",
            "mbmufroh",
            "deqwwqaturtb",
            "wfpflkuj",
            "tlqwhnajlptvsws",
            "gj",
            "vuqhlnrjqagbao",
            "luydcvtzkcnkmcyvzkkn",
            "zsvtnhsfduflugpajwc",
            "yipnxexcwnrdvsvr",
            "dbcixuqupddl",
            "xglzu",
            "bphdk",
            "ubfvhvjhgtu",
            "aaykwwkl",
            "mqolkexmmkpbukclixtp",
            "rnqwd",
            "pppdaufodyiw",
            "nbctcglvttk",
            "smbr",
            "szpkayfdfau",
            "ce",
            "snayfkgtnkvofjgsttb",
            "unwnlswvz",
            "a",
            "pltvvqzfvajipmffsv",
            "hvdxr",
            "cuvzg",
            "qzmxyyrquhohy",
            "hbbvdkhyyxdvbigutaoq",
            "lqryiaypeycugebh",
            "mcgtvgdem",
            "eset",
            "jnk",
            "uyflnlmqjsfwx",
            "mlxsdqfmci",
            "vppfywp",
            "iqngyzqk",
            "lgnjmtpncciwvd",
            "pxlptqnjqovjyi",
            "ldymvzqa",
            "ebh",
            "yukf",
            "hwkagsatbypof",
            "mkjdukaol",
            "vgnwymvld",
            "wmwcupv",
            "ldnpusiutmgcx",
            "zhgedd",
            "r",
            "cdzshqujl",
            "qnlzudmzaprp",
            "ixngzntzfdbkhzj",
            "cxpcbzsapcqevayol",
            "qrwjlb",
            "a",
            "pzemyx",
            "elagmlsmdwxcblw",
            "ah",
            "cymzomv",
            "abwbzurg",
            "ynw",
            "dtaitbpxcshbbeyfit",
            "lmjff",
            "stzjwixuzfjyrexjdo",
            "bpiefifulwke",
            "ulceqlhjmczzj",
            "eekxx",
            "snrdty",
            "rqreanm",
            "pqhapyfoyhtpud",
            "dchkiriy",
            "ldzoxjtupfgtm",
            "rpijtyhoobmvmqzt",
            "vplwkrqfqxlktujhok",
            "hbthtbdhmguit",
            "ivvvqyovvbkgeelro",
            "mjxnigf",
            "qkyymckjlbhkgfkj",
            "tsmhozxmq",
            "zmpljqknaskhec",
            "arnjxkie",
            "spogklivg",
            "krngxqmsisqj",
            "zhmdiwdphinpvp",
            "ocgnkpehnw",
            "oeyqlnh",
            "nvaxluvbv",
            "cilwxjgccuibuuqevk",
            "joounrfvursftqodq",
            "jabwchskrifvexxklshy",
            "msmgcqfexomyduhua",
            "qroljiwbndoloipelqsd",
            "yejuhwv",
            "geuvyvxrkqvnn",
            "ouhcxfehqvymbkpxgkjf",
            "grgqeaurpruvhabhhsb",
            "x",
            "gvicdczxkg",
            "qwgp",
            "qpmmjwnipwodk",
            "xbaouricd",
            "iixmkywblxelbuht",
            "pvd",
            "cjxgqcmm",
            "fmrqdavggglt",
            "hxbeobsffcuanqapi",
            "mxzlnuu",
            "wxujttwqxwzwthsmv"
        )
        val words2 = arrayOf(
            "ieahdxawxj",
            "djzwhhobr",
            "zlr",
            "cvdeveipedypmkfjgce",
            "ksnrwbmgefgz",
            "brf",
            "atciwicknt",
            "ykiywtebsuibtu",
            "hiqzolamsrg",
            "lajhj",
            "yraknmxnof",
            "wpqigcccogxvdamm",
            "vvg",
            "nvkfxsbdmcgpxiz",
            "jjau",
            "y",
            "kdtnqloxtqwsxprpjeel",
            "mdxpvkymyt",
            "qbayfhfdsxjcxwisaxib",
            "fowqtienfhxydlolxe",
            "fchkflwu",
            "pipuylvpauew",
            "apgceyubzneckp",
            "p",
            "evxepcymgvotkezvp",
            "qkjrnqkxtavvokjnnvu",
            "inkasqmk",
            "etsb",
            "oonrglhakqhmib",
            "qxujqwlgotekpz",
            "evvp",
            "yvcbbnbcekaag",
            "aed",
            "hzujfoov",
            "qfkkjmqplnkfigjd",
            "omrja",
            "ctfwuagcdvdzojqhwvc",
            "rqmchulzegup",
            "f",
            "nakgbuwebxlq",
            "uqvocnozimffbyubfmj",
            "nlclgghaavybhmrzql",
            "fcopzhovejihsoq",
            "zevdmaqthsvmvw",
            "cqlnfumvkxoef",
            "oskuzzutbaaqcbjrvrx",
            "pluweqbwronf",
            "upif",
            "fgogca",
            "gofw",
            "yhixhm",
            "ehuvxdbpwixwv",
            "ghqlvfwidwwfnvn",
            "srdxodfw",
            "uhhwogelyyy",
            "csnatbwedjmtyxgsjo",
            "llvdsbswaoowbfnpz",
            "hbr",
            "mibncoclsornfpgza",
            "pbrkyl",
            "awewbul",
            "ohxa",
            "nwwjj",
            "rvihqcmtglqocs",
            "bijuzme",
            "jvonae",
            "tiiwdceazgvcwg",
            "mjifriag",
            "xwextr",
            "gfktztuhmbxqaksf",
            "k",
            "hzj",
            "doypumttuciwwuorakp",
            "awdslxihpafymsmvtpx",
            "pzsyxgdvvjztmsr",
            "jzq",
            "yuzsqfriqkn",
            "jzd",
            "saavdjh",
            "dgxcmigreramacegpiur",
            "gvr",
            "talrqnwfvckle",
            "gvnoeztukmu",
            "efzditf",
            "bvasvhrhomwnzkf",
            "ovnujieecymgjibcrjde",
            "ozrzvbm",
            "klgyec",
            "mpemfd",
            "yyhfujutxd",
            "btvnehzdw",
            "rgfvyglpghfbqevjuyc",
            "wvyutcdvclaexf",
            "waxfwy",
            "bmakevryofxkisryzyrn",
            "ehbpfalbbnyvlaxs",
            "lvsrmanmpyebe",
            "custxljuenbomxa",
            "upinyrjceuoyenh",
            "sdguesgzxgp",
            "xvtp",
            "slrvxeuacjdoeoznptj",
            "cdzxfkhdcc",
            "tvmaefzis",
            "rgivnevefe",
            "lpzf",
            "bpiepovskroxexserkqk",
            "igfukjigihm",
            "ipbbyemnyulknng",
            "tvoqcdnssd",
            "boeiodwrknqi",
            "pofgnxtmlbxcgg",
            "klhhvkabeffn",
            "lyrvwlvdoodf",
            "wwwwaxcuvfpnuabfe",
            "sat",
            "kdvpvbjuteutrvd",
            "onk",
            "ckluvgvqzpmxdwqkmi",
            "jhgqgkhijnh",
            "joyoudpxrarzdjdjrx",
            "kreqnutqygyriyjfvv",
            "gpgsfb",
            "uexdsidcfcoasfqneqek",
            "qzwbnrfvjnrlo",
            "gzgc",
            "cur",
            "bqxbp",
            "wkxtlwunzzbmzyhoahm",
            "wbpcejvqlmoyqnakc",
            "ijajssmvjrseurgrhoax",
            "hihcfwqkpvxo",
            "zfc",
            "ipn",
            "ka",
            "zfvjwjjvqwckbvjpa",
            "erpzitkkfrrfocddfb",
            "xlcayjrmazxggno",
            "ensnvtcvudykdgeaewi",
            "cdd",
            "lcv",
            "uwjrqzsagedojsblfdgb",
            "zbnrsaokkkayn",
            "wvlkywm",
            "nqwpixqcgwvmayfy",
            "ekkzjepseczkbih",
            "brlox",
            "nedtuxfgq",
            "xcvitirtal",
            "kgmrfitehw",
            "cvd",
            "kemt",
            "gltaassmofbzhlkl",
            "kifqh",
            "jkljxckjui",
            "gekms",
            "aq",
            "nne",
            "yytkzcvgce",
            "zjolwjh",
            "ofyydpxdlaqlw",
            "fntfdc",
            "h",
            "fqvyx",
            "zresivxnys",
            "egmrwxwjczhiojfvs",
            "ozpxwhcqtmkx",
            "owge",
            "bufbpqvppmpzzzoa",
            "oyxyn",
            "pkspdqxku",
            "zzxrdjcgr",
            "qcfvtigap",
            "pzhfqrxspgltmkg",
            "hbjdnshbriqkkdgnda",
            "ypxuobo",
            "ejsyyzdtljrfgzvshi",
            "klnev",
            "hrzj",
            "zoaaqqioeltppadihaj",
            "crntpcxhblri",
            "xrtzvsklgzwji",
            "mdjn",
            "lwbksnqb",
            "ol",
            "eakcydfft",
            "ltvkc",
            "tmbrosxbbuvpqpd",
            "lcqlltscdblvyonfxysu",
            "pvimztqtffijtfrnk",
            "adl",
            "cdfsiqltypfche",
            "vtslcoliwqraacwklrll",
            "x",
            "dsqilmpmilbrvpt",
            "rwefjigrq",
            "uti",
            "uzpkoqzqxoc",
            "grgdbbqcfalwg",
            "abetfiswzrtgltgjbizq",
            "lzvxyacf",
            "excwunvuohvnbwohi",
            "ibfa",
            "kcduu",
            "tes",
            "rbnyhuoviofnxxbnt",
            "soigslsbvk",
            "bi",
            "zfxwxqyxa",
            "ggsppaven",
            "qbqxcsxgicppzgvd",
            "tggmytgvwrtx",
            "vvuldyjys",
            "qpeszffkmmzzao",
            "bsfjetwsvubwyehsyr",
            "wcrvsuqppyikqmev",
            "i",
            "svyj",
            "xjmpbujhdvlfs",
            "g",
            "hullon",
            "ymqenvjercscfz",
            "ijypfyvqskq",
            "rptmwregevhxegleik",
            "gdnmhnqpwowxne",
            "dlzbj",
            "wqedzdx",
            "ink",
            "eogmsngkfilrsemem",
            "mtsfhp",
            "ahuseyaqirmbyis",
            "deicodxiiac",
            "cniq",
            "jtqpmmkgwnsjw",
            "ajwemzutfpzmymjasjdr",
            "golhjrarmnu",
            "vttyawnkn",
            "jyrjndaipwryjg",
            "yongfoubx",
            "eip",
            "n",
            "f",
            "iybhoozzoghjzyixwqh",
            "qvrqm",
            "pdopadujozrs",
            "mglufzy",
            "bgirafzmqjxkkg",
            "s",
            "hcpl",
            "hmsbrokpvfbowutj",
            "sob",
            "fuy",
            "l",
            "q",
            "jyagvbfaxgadcbarhnix",
            "nnnztqwuhey",
            "wfisrnpbud",
            "lhodboafrknab",
            "gvqnvmrabbejkpig",
            "mhsvpy",
            "bpvwge",
            "yekwnkuwh",
            "ybrz",
            "bjgiokb",
            "ayhxchssp",
            "zn",
            "nneszkyxjcziznwvdu",
            "hjusughteguunzwpt",
            "jya",
            "opeujmcgemzsrhdkblx",
            "jsjjaln",
            "xhhzrcmixusbbeuzxpib",
            "qjazkrxdcrzlsjp",
            "zhvsloxtighjg",
            "boqzugdyow",
            "gkpurekr",
            "umutjifrzwuctemb",
            "tforyzoqkzzhx",
            "elfjilljeautv",
            "yomg",
            "gqrygcziuh",
            "kyyhgqezl",
            "qaltbokkuwoeqszopn",
            "wtbszobkxruughea",
            "nphwytt",
            "hxabufcdbzavp",
            "ebdvfzrna",
            "n",
            "ithjscdfqhvac",
            "npfzsmp",
            "qqjzfsnd",
            "xzyuzoqjh",
            "pljfbhdyf",
            "njssontdknb",
            "apels",
            "loloulrlbixt",
            "gnugzpkbuqtzpcc",
            "othfaxozzgxfbcmzz",
            "fmnzjf",
            "eifhfutrkndzyvgje",
            "wnzhfeuyp",
            "gkszzanmhgt",
            "xvv",
            "weekgqgamwm",
            "pecfkqkbbqbb",
            "hnamfhpooy",
            "ygdbuembmh",
            "bdpbkcvdvp",
            "samsaugzvu",
            "dnnwzexvgxmryop",
            "g",
            "ulzcsr",
            "isqwcgjhahw",
            "lovpxdqapohumrx",
            "bcnjzfzhjcpdroluxrty",
            "mtynkoyinwdzb",
            "wcxfoutsjqlyzkvhr",
            "cutogvmlx",
            "qnghkyqbzspsbbdcrlk",
            "kaiivxrosjcsupaivgn",
            "rugagg",
            "qwenoqmq",
            "otlo",
            "pskmxmsztmsicz",
            "ayaaglsqecuodksz",
            "hzkq",
            "rss",
            "qepnoqhouz",
            "zvhob",
            "f",
            "rawaopoxtxh",
            "cvmoorlrvrxwt",
            "mvhpnv",
            "hyt",
            "yzznn",
            "rrqooltybkt",
            "yhqnnc",
            "zkrkjhgogzrvbtht",
            "micozbrvbxnifg",
            "aflcrhujdhbvmejy",
            "tgikhr",
            "zrjblfnpewrvlvib",
            "wtucvf",
            "cfwxxxfhxn",
            "ih",
            "gtsfctllfwvg",
            "izxyucvhrhxsriv",
            "potevbjetnjqnswjmusm",
            "ugud",
            "xxplkbmtpanwhbweupkm",
            "khtakmcebolugtxkmpsm",
            "ovncupvfefpd",
            "nkojkbucat",
            "cg",
            "dugtjknj",
            "nsfnesmxsyl",
            "qoubk",
            "hmtwdjmuzdsfdtczby",
            "lb",
            "dtpgnhepykeuookznmdh",
            "zov",
            "htn",
            "onpetbuolucbnfilh",
            "ssvrn",
            "eslmmoxmrdgnqel",
            "oxijhiidt",
            "cvpwcayopqgvdj",
            "vpqc",
            "jlq",
            "k",
            "ozpsplaijmwpkitgmvq",
            "zr",
            "qudfjpfdlqigjpggfv",
            "dtmstilycb",
            "l",
            "qlfe",
            "nctkgugzghbbdv",
            "gjfq",
            "ntmil",
            "vbywhzokoepx",
            "wperiehzknbcyxsj",
            "vhcjgnzqfbrpnbibma",
            "momcvkvpusivchhlnlr",
            "gengyt",
            "wbmvwdsybypil",
            "uesdxsmsuplfeo",
            "ssxyqeyvhqtup",
            "hlmky",
            "fjnbnqrntg",
            "czsxgjbwvappaqvrrb",
            "vrpirr",
            "u",
            "tdjernbo",
            "oiwaqzlgg",
            "lvkvqpe",
            "mvyq",
            "leuynfhmoywvwecre",
            "eumb",
            "msiptuhoyubgtllvouwk",
            "uokjcvaxmuhuhmrpq",
            "oez",
            "n",
            "udqfxvphxgnw",
            "tz",
            "nfykjsqdodagjjtxyav",
            "pdqkzdmipfpgm",
            "coqqzjulhmrpgmvjbc",
            "xn",
            "cesfdch",
            "mpecvkquaqgwyhdnde",
            "tohiohnw",
            "kbgcfn",
            "fbniyglusjfwgc",
            "qasysptivkg",
            "siipnrdenqzgywcqtirn",
            "lhwbscyrun",
            "zcodummfjphmkkjt",
            "xewttjutwmrlutix",
            "jghc",
            "vqviv",
            "iuaf",
            "uptdhxrwsoljrencgxj",
            "yswmldfyucxngfeiryj",
            "hk",
            "oj",
            "ys",
            "ulbqjzk",
            "jogtnfohqgskvccts",
            "kyjfqxivfn",
            "jamecllhtzmbxvuncwp",
            "oodcxnmzstwp",
            "kzcia",
            "msmtanp",
            "hyafpl",
            "qbcz",
            "pomdpxfc",
            "bqalcyhuvoogbovzjqo",
            "hjzdynntmyclktho",
            "clfdfcqy",
            "rxbsxpjjubstgapjqr",
            "vlfa",
            "ie",
            "fsjbitmdhzypejqwlq",
            "kioaywuxqgemygshnoo",
            "ionanjia",
            "scgrceqgxxme",
            "kaqhzhkkpwkfisswr",
            "orgbec",
            "o",
            "bzr",
            "whfxpagoshxjqtgbapef",
            "xtjv",
            "mnjr",
            "zkzepgkaomji",
            "pdczidfjhocywxs",
            "xtiymotmdo",
            "te",
            "uakomshwgdp",
            "e",
            "njwnyfbiph",
            "nlwfouuwwhlsnnnj",
            "op",
            "sybuzsxjlxwgymclyfb",
            "uiwbig",
            "jsnmefrodwkfafaji",
            "yvqyhtf",
            "uyyoxgimzaaolelhtyo",
            "gglql",
            "wborcgdxrxjgufspnagr",
            "rcwfonund",
            "nilhmh",
            "tha",
            "iaj",
            "zyylxvjbwsemvpx",
            "cxanegfrgo",
            "rdeowrwcu",
            "haidgoaxzqrsz",
            "iqlyfwwhqozw",
            "klhuvnfimvgjnoplg",
            "xisugyly",
            "tl",
            "uqmbequqvnoui",
            "ahkiawktjgp",
            "phxdybxwbw",
            "kytihyweved",
            "evaqe",
            "kdxzkzylbhgf",
            "ljzhrionxikhuzfxrs",
            "zijdyflyyke",
            "wzarwlayxczum",
            "gplddujbavrceofgj",
            "axkreefydzhb",
            "eevxyqalriojaeu",
            "xyoszjtvohgasxiqcloj"
        )

        val pairs = listOf(
            mutableListOf("xyoszjtvohgasxiqcloj", "wxujttwqxwzwthsmv"),
            mutableListOf("mxzlnuu", "eevxyqalriojaeu"),
            mutableListOf("axkreefydzhb", "hxbeobsffcuanqapi"),
            mutableListOf("fmrqdavggglt", "gplddujbavrceofgj"),
            mutableListOf("cjxgqcmm", "wzarwlayxczum"),
            mutableListOf("pvd", "zijdyflyyke"),
            mutableListOf("iixmkywblxelbuht", "ljzhrionxikhuzfxrs"),
            mutableListOf("xbaouricd", "kdxzkzylbhgf"),
            mutableListOf("evaqe", "qpmmjwnipwodk"),
            mutableListOf("kytihyweved", "qwgp"),
            mutableListOf("phxdybxwbw", "gvicdczxkg"),
            mutableListOf("x", "ahkiawktjgp"),
            mutableListOf("uqmbequqvnoui", "grgqeaurpruvhabhhsb"),
            mutableListOf("tl", "ouhcxfehqvymbkpxgkjf"),
            mutableListOf("xisugyly", "geuvyvxrkqvnn"),
            mutableListOf("yejuhwv", "klhuvnfimvgjnoplg"),
            mutableListOf("qroljiwbndoloipelqsd", "iqlyfwwhqozw"),
            mutableListOf("haidgoaxzqrsz", "msmgcqfexomyduhua"),
            mutableListOf("jabwchskrifvexxklshy", "rdeowrwcu"),
            mutableListOf("cxanegfrgo", "joounrfvursftqodq"),
            mutableListOf("cilwxjgccuibuuqevk", "zyylxvjbwsemvpx"),
            mutableListOf("iaj", "nvaxluvbv"),
            mutableListOf("tha", "oeyqlnh"),
            mutableListOf("ocgnkpehnw", "nilhmh"),
            mutableListOf("rcwfonund", "zhmdiwdphinpvp"),
            mutableListOf("krngxqmsisqj", "wborcgdxrxjgufspnagr"),
            mutableListOf("spogklivg", "gglql"),
            mutableListOf("arnjxkie", "uyyoxgimzaaolelhtyo"),
            mutableListOf("yvqyhtf", "zmpljqknaskhec"),
            mutableListOf("jsnmefrodwkfafaji", "tsmhozxmq"),
            mutableListOf("uiwbig", "qkyymckjlbhkgfkj"),
            mutableListOf("sybuzsxjlxwgymclyfb", "mjxnigf"),
            mutableListOf("ivvvqyovvbkgeelro", "op"),
            mutableListOf("hbthtbdhmguit", "nlwfouuwwhlsnnnj"),
            mutableListOf("njwnyfbiph", "vplwkrqfqxlktujhok"),
            mutableListOf("e", "rpijtyhoobmvmqzt"),
            mutableListOf("uakomshwgdp", "ldzoxjtupfgtm"),
            mutableListOf("te", "dchkiriy"),
            mutableListOf("pqhapyfoyhtpud", "xtiymotmdo"),
            mutableListOf("rqreanm", "pdczidfjhocywxs"),
            mutableListOf("snrdty", "zkzepgkaomji"),
            mutableListOf("eekxx", "mnjr"),
            mutableListOf("xtjv", "ulceqlhjmczzj"),
            mutableListOf("bpiefifulwke", "whfxpagoshxjqtgbapef"),
            mutableListOf("stzjwixuzfjyrexjdo", "bzr"),
            mutableListOf("o", "lmjff"),
            mutableListOf("dtaitbpxcshbbeyfit", "orgbec"),
            mutableListOf("kaqhzhkkpwkfisswr", "ynw"),
            mutableListOf("abwbzurg", "scgrceqgxxme"),
            mutableListOf("cymzomv", "ionanjia"),
            mutableListOf("kioaywuxqgemygshnoo", "ah"),
            mutableListOf("elagmlsmdwxcblw", "fsjbitmdhzypejqwlq"),
            mutableListOf("ie", "pzemyx"),
            mutableListOf("vlfa", "a"),
            mutableListOf("qrwjlb", "rxbsxpjjubstgapjqr"),
            mutableListOf("cxpcbzsapcqevayol", "clfdfcqy"),
            mutableListOf("ixngzntzfdbkhzj", "hjzdynntmyclktho"),
            mutableListOf("bqalcyhuvoogbovzjqo", "qnlzudmzaprp"),
            mutableListOf("pomdpxfc", "cdzshqujl"),
            mutableListOf("qbcz", "r"),
            mutableListOf("zhgedd", "hyafpl"),
            mutableListOf("ldnpusiutmgcx", "msmtanp"),
            mutableListOf("kzcia", "wmwcupv"),
            mutableListOf("oodcxnmzstwp", "vgnwymvld"),
            mutableListOf("mkjdukaol", "jamecllhtzmbxvuncwp"),
            mutableListOf("hwkagsatbypof", "kyjfqxivfn"),
            mutableListOf("jogtnfohqgskvccts", "yukf"),
            mutableListOf("ebh", "ulbqjzk"),
            mutableListOf("ys", "ldymvzqa"),
            mutableListOf("pxlptqnjqovjyi", "oj"),
            mutableListOf("hk", "lgnjmtpncciwvd"),
            mutableListOf("yswmldfyucxngfeiryj", "iqngyzqk"),
            mutableListOf("vppfywp", "uptdhxrwsoljrencgxj"),
            mutableListOf("mlxsdqfmci", "iuaf"),
            mutableListOf("uyflnlmqjsfwx", "vqviv"),
            mutableListOf("jghc", "jnk"),
            mutableListOf("xewttjutwmrlutix", "eset"),
            mutableListOf("mcgtvgdem", "zcodummfjphmkkjt"),
            mutableListOf("lhwbscyrun", "lqryiaypeycugebh"),
            mutableListOf("siipnrdenqzgywcqtirn", "hbbvdkhyyxdvbigutaoq"),
            mutableListOf("qasysptivkg", "qzmxyyrquhohy"),
            mutableListOf("fbniyglusjfwgc", "cuvzg"),
            mutableListOf("kbgcfn", "hvdxr"),
            mutableListOf("pltvvqzfvajipmffsv", "tohiohnw"),
            mutableListOf("a", "mpecvkquaqgwyhdnde"),
            mutableListOf("cesfdch", "unwnlswvz"),
            mutableListOf("xn", "snayfkgtnkvofjgsttb"),
            mutableListOf("coqqzjulhmrpgmvjbc", "ce"),
            mutableListOf("szpkayfdfau", "pdqkzdmipfpgm"),
            mutableListOf("smbr", "nfykjsqdodagjjtxyav"),
            mutableListOf("nbctcglvttk", "tz"),
            mutableListOf("udqfxvphxgnw", "pppdaufodyiw"),
            mutableListOf("rnqwd", "n"),
            mutableListOf("oez", "mqolkexmmkpbukclixtp"),
            mutableListOf("uokjcvaxmuhuhmrpq", "aaykwwkl"),
            mutableListOf("msiptuhoyubgtllvouwk", "ubfvhvjhgtu"),
            mutableListOf("eumb", "bphdk"),
            mutableListOf("xglzu", "leuynfhmoywvwecre"),
            mutableListOf("dbcixuqupddl", "mvyq"),
            mutableListOf("yipnxexcwnrdvsvr", "lvkvqpe"),
            mutableListOf("zsvtnhsfduflugpajwc", "oiwaqzlgg"),
            mutableListOf("luydcvtzkcnkmcyvzkkn", "tdjernbo"),
            mutableListOf("vuqhlnrjqagbao", "u"),
            mutableListOf("vrpirr", "gj"),
            mutableListOf("tlqwhnajlptvsws", "czsxgjbwvappaqvrrb"),
            mutableListOf("fjnbnqrntg", "wfpflkuj"),
            mutableListOf("hlmky", "deqwwqaturtb"),
            mutableListOf("ssxyqeyvhqtup", "mbmufroh"),
            mutableListOf("uesdxsmsuplfeo", "eemrmqjvq"),
            mutableListOf("wbmvwdsybypil", "usedqbhoxjaawqodbs"),
            mutableListOf("dxxnhbmqnzupnac", "gengyt"),
            mutableListOf("cssqdfdcwc", "momcvkvpusivchhlnlr"),
            mutableListOf("vhcjgnzqfbrpnbibma", "nidlewlbyqjcidduhnxh"),
            mutableListOf("azpspsumoawvpko", "wperiehzknbcyxsj"),
            mutableListOf("vbywhzokoepx", "fmvyu"),
            mutableListOf("wtrjssuelmfuk", "ntmil"),
            mutableListOf("ohqosywlniiwi", "gjfq"),
            mutableListOf("iwwoqjgwrxdtblweui", "nctkgugzghbbdv"),
            mutableListOf("cfadzvzkeo", "qlfe"),
            mutableListOf("rbzczaesxtuqctemupc", "l"),
            mutableListOf("owvxqegncxiluiuvez", "dtmstilycb"),
            mutableListOf("qudfjpfdlqigjpggfv", "qy"),
            mutableListOf("zr", "fzxsmaqo"),
            mutableListOf("dkcox", "ozpsplaijmwpkitgmvq"),
            mutableListOf("k", "i"),
            mutableListOf("bktaotdpdceasft", "jlq"),
            mutableListOf("zjkegjnobyfxcji", "vpqc"),
            mutableListOf("btbgbjnf", "cvpwcayopqgvdj"),
            mutableListOf("oxijhiidt", "p"),
            mutableListOf("eslmmoxmrdgnqel", "zfseshwgaqwwdoi"),
            mutableListOf("ssvrn", "fjolgalpaugklukaz"),
            mutableListOf("xyudyhqlqwacl", "onpetbuolucbnfilh"),
            mutableListOf("htn", "z"),
            mutableListOf("kievpe", "zov"),
            mutableListOf("ltlewuxuexccfiht", "dtpgnhepykeuookznmdh"),
            mutableListOf("jzihwh", "lb"),
            mutableListOf("xhbmsxgqlrc", "hmtwdjmuzdsfdtczby"),
            mutableListOf("jga", "qoubk"),
            mutableListOf("nsfnesmxsyl", "mswttfe"),
            mutableListOf("optxlljafpdd", "dugtjknj"),
            mutableListOf("cg", "gvnvoatskqrmp"),
            mutableListOf("nkojkbucat", "hmtwe"),
            mutableListOf("ovncupvfefpd", "x"),
            mutableListOf("khtakmcebolugtxkmpsm", "pxzqbh"),
            mutableListOf("bkuzk", "xxplkbmtpanwhbweupkm"),
            mutableListOf("ugud", "pwcrdqebphxnjqmejb"),
            mutableListOf("rism", "potevbjetnjqnswjmusm"),
            mutableListOf("ialcymrzzveacskteax", "izxyucvhrhxsriv"),
            mutableListOf("lfhcl", "gtsfctllfwvg"),
            mutableListOf("s", "ih"),
            mutableListOf("vmsxlobeqawbynzve", "cfwxxxfhxn"),
            mutableListOf("ogzggbejqnulxqsafuk", "wtucvf"),
            mutableListOf("r", "zrjblfnpewrvlvib"),
            mutableListOf("cad", "tgikhr"),
            mutableListOf("aflcrhujdhbvmejy", "gpiqywwskhomqnupomq"),
            mutableListOf("micozbrvbxnifg", "klmjypf"),
            mutableListOf("zkrkjhgogzrvbtht", "zwoimowz"),
            mutableListOf("yhqnnc", "uyyfdpgkxmmhhcaz"),
            mutableListOf("rrqooltybkt", "msfmwrjqdefkebl"),
            mutableListOf("mfkhrtmdtrjwnsnuem", "yzznn"),
            mutableListOf("ivjdvijlbfjsdbcqqud", "hyt"),
            mutableListOf("mvhpnv", "iylqb"),
            mutableListOf("cvmoorlrvrxwt", "yg"),
            mutableListOf("rawaopoxtxh", "zlzx"),
            mutableListOf("cpzg", "f"),
            mutableListOf("rfbjueoivkmbrhd", "zvhob"),
            mutableListOf("bkahzmfylmkglnmogndn", "qepnoqhouz"),
            mutableListOf("rss", "qfxstgwhycpqksfiy"),
            mutableListOf("ahojsdthxcfqkwhgfwt", "hzkq"),
            mutableListOf("nvkxsrmgl", "ayaaglsqecuodksz"),
            mutableListOf("pskmxmsztmsicz", "aedrqugdgwhzsotx"),
            mutableListOf("bbahbwvhoub", "otlo"),
            mutableListOf("qwenoqmq", "lhhlzzwgmvzqodrr"),
            mutableListOf("ebdfskqm", "rugagg"),
            mutableListOf("kaiivxrosjcsupaivgn", "jbxcakghqewctmhbryzf"),
            mutableListOf("qnghkyqbzspsbbdcrlk", "xlmfaylnd"),
            mutableListOf("cutogvmlx", "tkkchajzgnl"),
            mutableListOf("wcxfoutsjqlyzkvhr", "uhrlrlpqp"),
            mutableListOf("mtynkoyinwdzb", "uxenxwxomhrmf"),
            mutableListOf("bcnjzfzhjcpdroluxrty", "e"),
            mutableListOf("duuixykph", "lovpxdqapohumrx"),
            mutableListOf("isqwcgjhahw", "oxbxdowzhfi"),
            mutableListOf("afbvwzlcyoafbjevfsk", "ulzcsr"),
            mutableListOf("uywxtad", "g"),
            mutableListOf("zmujdlwcwmntuk", "dnnwzexvgxmryop"),
            mutableListOf("samsaugzvu", "jucvirvlqgyvrxtl"),
            mutableListOf("efwvkcqeaojrj", "bdpbkcvdvp"),
            mutableListOf("ygdbuembmh", "huwoznvqsqertr"),
            mutableListOf("liqvnjiaxxbvc", "hnamfhpooy"),
            mutableListOf("v", "pecfkqkbbqbb"),
            mutableListOf("weekgqgamwm", "ypwldfgoqn"),
            mutableListOf("cksj", "xvv"),
            mutableListOf("utkpnlqzcqjl", "gkszzanmhgt"),
            mutableListOf("d", "wnzhfeuyp"),
            mutableListOf("jvjkbuyigqbsljduugt", "eifhfutrkndzyvgje"),
            mutableListOf("j", "fmnzjf"),
            mutableListOf("qyakiwu", "othfaxozzgxfbcmzz"),
            mutableListOf("znijktfivkcyroaq", "gnugzpkbuqtzpcc"),
            mutableListOf("gang", "loloulrlbixt"),
            mutableListOf("apels", "mzntgnxcudlvglbddwpw"),
            mutableListOf("drmiofi", "njssontdknb"),
            mutableListOf("pljfbhdyf", "auxru"),
            mutableListOf("giebneqyyusxfi", "xzyuzoqjh"),
            mutableListOf("qqjzfsnd", "jeibnmylbr"),
            mutableListOf("npfzsmp", "htogbrzknm"),
            mutableListOf("jbtnvijpphujhm", "ithjscdfqhvac"),
            mutableListOf("mtktqttvjmtkfwhgpihq", "n"),
            mutableListOf("sbgdj", "ebdvfzrna"),
            mutableListOf("qdxnkbhozg", "hxabufcdbzavp"),
            mutableListOf("nphwytt", "mfilhjaqdhxembiw"),
            mutableListOf("wtbszobkxruughea", "vxukjn"),
            mutableListOf("mcdcpiuruvdnmobhz", "qaltbokkuwoeqszopn"),
            mutableListOf("dprqi", "kyyhgqezl"),
            mutableListOf("gqrygcziuh", "lgmjp"),
            mutableListOf("yomg", "fncwcuixzqgwqchif"),
            mutableListOf("elfjilljeautv", "vhwavpag"),
            mutableListOf("vxeiyliihvup", "tforyzoqkzzhx"),
            mutableListOf("umutjifrzwuctemb", "uamwsyvzwhaz"),
            mutableListOf("gkpurekr", "ljqpavy"),
            mutableListOf("yvuxjmaczkpxc", "boqzugdyow"),
            mutableListOf("lmhkbgeouyhk", "zhvsloxtighjg"),
            mutableListOf("qjazkrxdcrzlsjp", "zrhzucznpnjcmyfemojo"),
            mutableListOf("xhhzrcmixusbbeuzxpib", "ekynynfmqt"),
            mutableListOf("tuovsrgfdc", "jsjjaln"),
            mutableListOf("vhyzahdqqcwhbspb", "opeujmcgemzsrhdkblx"),
            mutableListOf("jya", "z"),
            mutableListOf("hjusughteguunzwpt", "vaedlcrzdtzesbt"),
            mutableListOf("nneszkyxjcziznwvdu", "ezjiiflnqvvwbta"),
            mutableListOf("hy", "zn"),
            mutableListOf("ayhxchssp", "txearitnmzpdteqhy"),
            mutableListOf("bjgiokb", "tphsnrjyensfcagcmcr"),
            mutableListOf("ybrz", "tlaxgjnruhyeprmbbrh"),
            mutableListOf("wuzvkbjrmnbn", "yekwnkuwh"),
            mutableListOf("bpvwge", "qtijvjcuyyxptz"),
            mutableListOf("zndddcccs", "mhsvpy"),
            mutableListOf("gvqnvmrabbejkpig", "gnyxzkdntj"),
            mutableListOf("lhodboafrknab", "rojfbulrcziyubmp"),
            mutableListOf("wfisrnpbud", "sxsegckaiymklqz"),
            mutableListOf("nnnztqwuhey", "gywtqwausjzy"),
            mutableListOf("lplfuekjxou", "jyagvbfaxgadcbarhnix"),
            mutableListOf("felorhelowdrljr", "q"),
            mutableListOf("l", "vcxmaonvgk"),
            mutableListOf("fuy", "wdpqetxiqqop"),
            mutableListOf("sob", "ostudmhji"),
            mutableListOf("hmsbrokpvfbowutj", "dnfoqesr"),
            mutableListOf("tvqznovxlcd", "hcpl"),
            mutableListOf("hfdxagxr", "s"),
            mutableListOf("bgirafzmqjxkkg", "ivymhwxtbpn"),
            mutableListOf("zdxaozbcfhzx", "mglufzy"),
            mutableListOf("pdopadujozrs", "cu"),
            mutableListOf("qvrqm", "kgspktobxihjtnvh"),
            mutableListOf("iybhoozzoghjzyixwqh", "ndmd"),
            mutableListOf("f", "uxzbocbihlehl"),
            mutableListOf("zxcrrrnxwjvxiapkka", "n"),
            mutableListOf("sjrxbwhrdr", "eip"),
            mutableListOf("yongfoubx", "amvjurctaremecyop"),
            mutableListOf("hqwhmosezoeihxkjola", "jyrjndaipwryjg"),
            mutableListOf("mqho", "vttyawnkn"),
            mutableListOf("golhjrarmnu", "jtpr"),
            mutableListOf("siwxehy", "ajwemzutfpzmymjasjdr"),
            mutableListOf("luzztuahacmkpregj", "jtqpmmkgwnsjw"),
            mutableListOf("cniq", "vgfkqntltoarjlganmx"),
            mutableListOf("deicodxiiac", "wqhogyxhkhvoqcb"),
            mutableListOf("w", "ahuseyaqirmbyis"),
            mutableListOf("kdjwqmclz", "mtsfhp"),
            mutableListOf("eogmsngkfilrsemem", "pkyrmtyfleikoljulq"),
            mutableListOf("ac", "ink"),
            mutableListOf("pimxvbkrm", "wqedzdx"),
            mutableListOf("dlzbj", "sqxbownbeqxpp"),
            mutableListOf("ffpl", "gdnmhnqpwowxne"),
            mutableListOf("rptmwregevhxegleik", "jsixuxzdoe"),
            mutableListOf("nloevyoemx", "ijypfyvqskq"),
            mutableListOf("ymqenvjercscfz", "nkprvxstnev"),
            mutableListOf("hullon", "qfffmybpekabbuetjxa"),
            mutableListOf("ygypmqkyoqy", "g"),
            mutableListOf("xjmpbujhdvlfs", "gbvxbzbwxnnca"),
            mutableListOf("qndescuxugfoewxb", "svyj"),
            mutableListOf("i", "yoq"),
            mutableListOf("avkbzthupawtc", "wcrvsuqppyikqmev"),
            mutableListOf("ojejbx", "bsfjetwsvubwyehsyr"),
            mutableListOf("drcaqiswxe", "qpeszffkmmzzao"),
            mutableListOf("c", "vvuldyjys"),
            mutableListOf("fxq", "tggmytgvwrtx"),
            mutableListOf("zmcdzx", "qbqxcsxgicppzgvd"),
            mutableListOf("ggsppaven", "oqjvopvnwmpuhvszgi"),
            mutableListOf("zfxwxqyxa", "upcdponnfzrhyx"),
            mutableListOf("bi", "qrl"),
            mutableListOf("rzpmghrpmxwc", "soigslsbvk"),
            mutableListOf("ouhdydmjsmtkzk", "rbnyhuoviofnxxbnt"),
            mutableListOf("tes", "lgahxyipygnumuq"),
            mutableListOf("kcduu", "yxu"),
            mutableListOf("uhxukklyy", "ibfa"),
            mutableListOf("excwunvuohvnbwohi", "jlrfoivnopskfrga"),
            mutableListOf("p", "lzvxyacf"),
            mutableListOf("abetfiswzrtgltgjbizq", "ykrznlimf"),
            mutableListOf("wwmehvaqeihwnaoxvted", "grgdbbqcfalwg"),
            mutableListOf("oxwbodmqqicwh", "uzpkoqzqxoc"),
            mutableListOf("uti", "dcclr"),
            mutableListOf("rwefjigrq", "bnxtrpst"),
            mutableListOf("pzl", "dsqilmpmilbrvpt"),
            mutableListOf("q", "x"),
            mutableListOf("glplhqvwq", "vtslcoliwqraacwklrll"),
            mutableListOf("cdfsiqltypfche", "nooezkhrfimg"),
            mutableListOf("adl", "hfiwvwglvdmt"),
            mutableListOf("hbg", "pvimztqtffijtfrnk"),
            mutableListOf("lcqlltscdblvyonfxysu", "yzfemhkmbxqqwuibt"),
            mutableListOf("qqfgmusddn", "tmbrosxbbuvpqpd"),
            mutableListOf("ltvkc", "wljnkhqrzjpawq"),
            mutableListOf("eakcydfft", "vvjszhnpfrbu"),
            mutableListOf("ol", "suymrbbcouzcfjsiog"),
            mutableListOf("xocvjoujdqnk", "lwbksnqb"),
            mutableListOf("mdjn", "iyqtitjyitbzxgzdcp"),
            mutableListOf("hqmhdwlyadp", "xrtzvsklgzwji"),
            mutableListOf("crntpcxhblri", "q"),
            mutableListOf("osqkanxrowymhqwl", "zoaaqqioeltppadihaj"),
            mutableListOf("cnnxfszbmzhjew", "hrzj"),
            mutableListOf("vqsrqtmmam", "klnev"),
            mutableListOf("utplueq", "ejsyyzdtljrfgzvshi"),
            mutableListOf("zgmjd", "ypxuobo"),
            mutableListOf("hbjdnshbriqkkdgnda", "ftfzekaingyljtxwix"),
            mutableListOf("wmnczxakddvmmajg", "pzhfqrxspgltmkg"),
            mutableListOf("smpwxarpolyew", "qcfvtigap"),
            mutableListOf("ebof", "zzxrdjcgr"),
            mutableListOf("pkrbseljovsevzdxqds", "pkspdqxku"),
            mutableListOf("oyxyn", "eslwspkg"),
            mutableListOf("eozx", "bufbpqvppmpzzzoa"),
            mutableListOf("owge", "joutnbrtwfxpyskktopw"),
            mutableListOf("ozpxwhcqtmkx", "tvradkk"),
            mutableListOf("utlqbjnaxw", "egmrwxwjczhiojfvs"),
            mutableListOf("zresivxnys", "jki"),
            mutableListOf("ewhyznlamihuqtb", "fqvyx"),
            mutableListOf("h", "pzibv"),
            mutableListOf("qmc", "fntfdc"),
            mutableListOf("ofyydpxdlaqlw", "pqvoes"),
            mutableListOf("tkkyrekeqz", "zjolwjh"),
            mutableListOf("ynuyrzahviwyhfu", "yytkzcvgce"),
            mutableListOf("nne", "mpfdtl"),
            mutableListOf("oikhbtjhdcnw", "aq"),
            mutableListOf("d", "gekms"),
            mutableListOf("jkljxckjui", "jjfplanrtlxdugb"),
            mutableListOf("kifqh", "vtgedmysfddjipkvnqeh"),
            mutableListOf("wlixhyufmrrw", "gltaassmofbzhlkl"),
            mutableListOf("kemt", "edufjuxyrxtapftzmg"),
            mutableListOf("cvd", "ftl"),
            mutableListOf("kgmrfitehw", "qtvimffxy"),
            mutableListOf("xcvitirtal", "kkbjrjtz"),
            mutableListOf("hwiylrzryjxg", "nedtuxfgq"),
            mutableListOf("kcckxtbieakkibgvt", "brlox"),
            mutableListOf("ekkzjepseczkbih", "po"),
            mutableListOf("ypdplprqmd", "nqwpixqcgwvmayfy"),
            mutableListOf("gpiqjkcsgydkykh", "wvlkywm"),
            mutableListOf("zbnrsaokkkayn", "xpiq"),
            mutableListOf("nhknajjywhye", "uwjrqzsagedojsblfdgb"),
            mutableListOf("gfbojeo", "lcv"),
            mutableListOf("cdd", "ezfqkf"),
            mutableListOf("ensnvtcvudykdgeaewi", "lwsfthm"),
            mutableListOf("xlcayjrmazxggno", "xhguqsopvslfyidob"),
            mutableListOf("xqctom", "erpzitkkfrrfocddfb"),
            mutableListOf("prucjqvfzl", "zfvjwjjvqwckbvjpa"),
            mutableListOf("wozexymucaiqqv", "ka"),
            mutableListOf("lwdonikd", "ipn"),
            mutableListOf("zfc", "kbonuyxzzovxa"),
            mutableListOf("ppbelm", "hihcfwqkpvxo"),
            mutableListOf("gwwwjuaauoml", "ijajssmvjrseurgrhoax"),
            mutableListOf("vjsipg", "wbpcejvqlmoyqnakc"),
            mutableListOf("wkxtlwunzzbmzyhoahm", "bfasvganyah"),
            mutableListOf("bqxbp", "p"),
            mutableListOf("bsrijei", "cur"),
            mutableListOf("hvrn", "gzgc"),
            mutableListOf("eqty", "qzwbnrfvjnrlo"),
            mutableListOf("r", "uexdsidcfcoasfqneqek"),
            mutableListOf("mhjbdealnxunxgem", "gpgsfb"),
            mutableListOf("uatcuscnxeeotaear", "kreqnutqygyriyjfvv"),
            mutableListOf("camg", "joyoudpxrarzdjdjrx"),
            mutableListOf("jhgqgkhijnh", "dwytkwou"),
            mutableListOf("ckluvgvqzpmxdwqkmi", "espuxjbjaydfwnyb"),
            mutableListOf("onk", "quqfcgtrrdsphf"),
            mutableListOf("kdvpvbjuteutrvd", "sqicc"),
            mutableListOf("qwmlb", "sat"),
            mutableListOf("wwwwaxcuvfpnuabfe", "meamxdkbcgkblnaiizz"),
            mutableListOf("ifkixrjyt", "lyrvwlvdoodf"),
            mutableListOf("xzqyuequpcesbizo", "klhhvkabeffn"),
            mutableListOf("zjfhmdpdubqpcrljs", "pofgnxtmlbxcgg"),
            mutableListOf("boeiodwrknqi", "fdbhezob"),
            mutableListOf("pmicfgtwn", "tvoqcdnssd"),
            mutableListOf("ktzphyhixqwlrloei", "ipbbyemnyulknng"),
            mutableListOf("igfukjigihm", "dcqqzadoauy"),
            mutableListOf("bpiepovskroxexserkqk", "bpkgj"),
            mutableListOf("lpzf", "gfw"),
            mutableListOf("rgivnevefe", "cbnlyetyzbxpxr"),
            mutableListOf("tvmaefzis", "alrezbetebbpldhqsqpf"),
            mutableListOf("swclnguodlvt", "cdzxfkhdcc"),
            mutableListOf("slrvxeuacjdoeoznptj", "agibvpfiepf"),
            mutableListOf("nuviwitjqvber", "xvtp"),
            mutableListOf("yuxdsva", "sdguesgzxgp"),
            mutableListOf("w", "upinyrjceuoyenh"),
            mutableListOf("kwcrpizmocx", "custxljuenbomxa"),
            mutableListOf("cn", "lvsrmanmpyebe"),
            mutableListOf("ehbpfalbbnyvlaxs", "pptwubqvrecgwdddyp"),
            mutableListOf("bmakevryofxkisryzyrn", "kopgduixakgicbdraf"),
            mutableListOf("waxfwy", "vksdvnglooqxqeymtq"),
            mutableListOf("wvyutcdvclaexf", "opcnrtguzrccyfkbtx"),
            mutableListOf("c", "rgfvyglpghfbqevjuyc"),
            mutableListOf("d", "btvnehzdw"),
            mutableListOf("rnzjuwzlxcfmxcrchr", "yyhfujutxd"),
            mutableListOf("mpemfd", "ivnubphldtiggb"),
            mutableListOf("klgyec", "a"),
            mutableListOf("ozrzvbm", "futaqwfflrdevipch"),
            mutableListOf("ovnujieecymgjibcrjde", "xlcdgqdacolughoz"),
            mutableListOf("oob", "bvasvhrhomwnzkf"),
            mutableListOf("efzditf", "qanfai"),
            mutableListOf("gvnoeztukmu", "kepvgxvbyp"),
            mutableListOf("talrqnwfvckle", "rbyjeozhqffsv"),
            mutableListOf("gvr", "lvbg"),
            mutableListOf("dgxcmigreramacegpiur", "dfxmagdbcowigwloehko"),
            mutableListOf("saavdjh", "ktyuqcyilcsoxc"),
            mutableListOf("ldvg", "jzd"),
            mutableListOf("atiozgwsciqhpier", "yuzsqfriqkn"),
            mutableListOf("jzq", "jbd"),
            mutableListOf("num", "pzsyxgdvvjztmsr"),
            mutableListOf("awdslxihpafymsmvtpx", "lxo"),
            mutableListOf("doypumttuciwwuorakp", "sstojwkonka"),
            mutableListOf("p", "hzj"),
            mutableListOf("k", "ejj"),
            mutableListOf("gfktztuhmbxqaksf", "ocshmsrfatzuskmd"),
            mutableListOf("xwextr", "lukogbni"),
            mutableListOf("mjifriag", "gvgcohqcldhxgkh"),
            mutableListOf("mkexxknaruheiyxnfx", "tiiwdceazgvcwg"),
            mutableListOf("jvonae", "cwtvje"),
            mutableListOf("bijuzme", "v"),
            mutableListOf("rvihqcmtglqocs", "ooccshlkcbftm"),
            mutableListOf("nwwjj", "auvqb"),
            mutableListOf("ohxa", "pedwpywglaeokdvbzni"),
            mutableListOf("nvh", "awewbul"),
            mutableListOf("pbrkyl", "hvatvzkbrxwiuazxbkq"),
            mutableListOf("mn", "mibncoclsornfpgza"),
            mutableListOf("hbr", "wxgkuhqwazwzdvzll"),
            mutableListOf("pynzkxxzqrysxhvpfvx", "llvdsbswaoowbfnpz"),
            mutableListOf("csnatbwedjmtyxgsjo", "nwsij"),
            mutableListOf("uhhwogelyyy", "lagjgiolyawffgmqmhva"),
            mutableListOf("mcspamhx", "srdxodfw"),
            mutableListOf("ghqlvfwidwwfnvn", "dipsedhofmqwxrygpoos"),
            mutableListOf("uzzzbvmxhwqazsfahbl", "ehuvxdbpwixwv"),
            mutableListOf("dmyvtjjxyzunkcfcq", "yhixhm"),
            mutableListOf("zpilljxbrckyd", "gofw"),
            mutableListOf("fgogca", "rfeyvfnnjdiethd"),
            mutableListOf("pcbfdtqzcqixxvbcq", "upif"),
            mutableListOf("wj", "pluweqbwronf"),
            mutableListOf("vmhwrkovbxjzvo", "oskuzzutbaaqcbjrvrx"),
            mutableListOf("pjswidphndhiuam", "cqlnfumvkxoef"),
            mutableListOf("zevdmaqthsvmvw", "pjab"),
            mutableListOf("zolvvdwx", "fcopzhovejihsoq"),
            mutableListOf("nlclgghaavybhmrzql", "rmhg"),
            mutableListOf("wsmcgdhrmrvbwgo", "uqvocnozimffbyubfmj"),
            mutableListOf("nakgbuwebxlq", "adronmoqp"),
            mutableListOf("awgthxflyktg", "f"),
            mutableListOf("jxsj", "rqmchulzegup"),
            mutableListOf("fymwy", "ctfwuagcdvdzojqhwvc"),
            mutableListOf("yrymuj", "omrja"),
            mutableListOf("g", "qfkkjmqplnkfigjd"),
            mutableListOf("hzujfoov", "wnafksi"),
            mutableListOf("anzquvbrmuvvccmnpqc", "aed"),
            mutableListOf("yvcbbnbcekaag", "grtxpwzg"),
            mutableListOf("evvp", "ishnxw"),
            mutableListOf("euzw", "qxujqwlgotekpz"),
            mutableListOf("oojxbritzftdkn", "oonrglhakqhmib"),
            mutableListOf("epnwxogbp", "etsb"),
            mutableListOf("inkasqmk", "ejjanjyualmouscfbs"),
            mutableListOf("qkjrnqkxtavvokjnnvu", "tgdkksuosjcsvphibf"),
            mutableListOf("evxepcymgvotkezvp", "oyyoines"),
            mutableListOf("p", "hty"),
            mutableListOf("apgceyubzneckp", "hmbdpbvswnqlctfurzju"),
            mutableListOf("sezgsulyganlodx", "pipuylvpauew"),
            mutableListOf("lxz", "fchkflwu"),
            mutableListOf("fowqtienfhxydlolxe", "sjunp"),
            mutableListOf("rvp", "qbayfhfdsxjcxwisaxib"),
            mutableListOf("mdxpvkymyt", "esnedvvmujxd"),
            mutableListOf("hjrgoxwqjscnbezqs", "kdtnqloxtqwsxprpjeel"),
            mutableListOf("tmagtnhpxxyxyhqbxrve", "y"),
            mutableListOf("jjau", "xcagsainqvjiubhhqz"),
            mutableListOf("nvkfxsbdmcgpxiz", "tvqzkrrcbxxfhxpth"),
            mutableListOf("thfxpcduq", "vvg"),
            mutableListOf("cdcamkwgwwlylqfrpgu", "wpqigcccogxvdamm"),
            mutableListOf("yraknmxnof", "samxstlsegphtpav"),
            mutableListOf("lajhj", "qpcioqvgzwbgn"),
            mutableListOf("lvwr", "hiqzolamsrg"),
            mutableListOf("ykiywtebsuibtu", "wikmwvpumhmcqim"),
            mutableListOf("ttghzzzatlrklrowdcee", "atciwicknt"),
            mutableListOf("afobhjkk", "brf"),
            mutableListOf("ksnrwbmgefgz", "qmshgrymnbq"),
            mutableListOf("jaweoprvmy", "cvdeveipedypmkfjgce"),
            mutableListOf("ulfurrnvyq", "zlr"),
            mutableListOf("djzwhhobr", "jtctwaf"),
            mutableListOf("ieahdxawxj", "ujcjiroxroclwymggqk"),
            mutableListOf("hwiylrzryjxg", "rxbsxpjjubstgapjqr"),
            mutableListOf("smpwxarpolyew", "cvd"),
            mutableListOf("pqvoes", "ebdvfzrna"),
            mutableListOf("ltlewuxuexccfiht", "tmbrosxbbuvpqpd"),
            mutableListOf("dipsedhofmqwxrygpoos", "ovnujieecymgjibcrjde"),
            mutableListOf("swclnguodlvt", "uqvocnozimffbyubfmj"),
            mutableListOf("c", "omrja"),
            mutableListOf("a", "mtynkoyinwdzb"),
            mutableListOf("ygypmqkyoqy", "dlzbj"),
            mutableListOf("bsrijei", "zresivxnys"),
            mutableListOf("wljnkhqrzjpawq", "vbywhzokoepx"),
            mutableListOf("mkjdukaol", "klhuvnfimvgjnoplg"),
            mutableListOf("espuxjbjaydfwnyb", "vqviv"),
            mutableListOf("a", "bsfjetwsvubwyehsyr"),
            mutableListOf("v", "rgivnevefe"),
            mutableListOf("auxru", "khtakmcebolugtxkmpsm"),
            mutableListOf("bkahzmfylmkglnmogndn", "apgceyubzneckp"),
            mutableListOf("x", "bpvwge"),
            mutableListOf("kopgduixakgicbdraf", "k"),
            mutableListOf("fymwy", "tmbrosxbbuvpqpd"),
            mutableListOf("rqreanm", "pljfbhdyf"),
            mutableListOf("kcckxtbieakkibgvt", "rbnyhuoviofnxxbnt"),
            mutableListOf("x", "haidgoaxzqrsz"),
            mutableListOf("wfpflkuj", "umutjifrzwuctemb"),
            mutableListOf("ldymvzqa", "n"),
            mutableListOf("snayfkgtnkvofjgsttb", "vvuldyjys"),
            mutableListOf("wlixhyufmrrw", "qfkkjmqplnkfigjd"),
            mutableListOf("luzztuahacmkpregj", "adl"),
            mutableListOf("vvjszhnpfrbu", "ieahdxawxj"),
            mutableListOf("kwcrpizmocx", "jhgqgkhijnh"),
            mutableListOf("gvnvoatskqrmp", "xtiymotmdo"),
            mutableListOf("owvxqegncxiluiuvez", "zrjblfnpewrvlvib"),
            mutableListOf("r", "ithjscdfqhvac"),
            mutableListOf("nvkxsrmgl", "nedtuxfgq"),
            mutableListOf("tvqznovxlcd", "ljzhrionxikhuzfxrs"),
            mutableListOf("pmicfgtwn", "tes"),
            mutableListOf("wqhogyxhkhvoqcb", "hxabufcdbzavp"),
            mutableListOf("mkjdukaol", "kioaywuxqgemygshnoo"),
            mutableListOf("kkbjrjtz", "gglql"),
            mutableListOf("v", "ayaaglsqecuodksz"),
            mutableListOf("qfxstgwhycpqksfiy", "otlo"),
            mutableListOf("pltvvqzfvajipmffsv", "pomdpxfc"),
            mutableListOf("euzw", "xtjv"),
            mutableListOf("nbctcglvttk", "hyt"),
            mutableListOf("iixmkywblxelbuht", "jghc"),
            mutableListOf("zmpljqknaskhec", "othfaxozzgxfbcmzz"),
            mutableListOf("eset", "bdpbkcvdvp"),
            mutableListOf("uywxtad", "rgfvyglpghfbqevjuyc"),
            mutableListOf("unwnlswvz", "boeiodwrknqi"),
            mutableListOf("ivymhwxtbpn", "rxbsxpjjubstgapjqr")
        )
        assertTrue(Solution().isSentenceSimilarity(words1, words2, pairs))
    }
}
