import org.junit.jupiter.api.Test
import kotlin.test.*

class SolutionTest {

    @Test
    fun BasicTests() {
        assertEquals("HGBCACABCACABCACAF", Solution().decompressString("HG[3|B[2|CA]]F"))
        assertEquals("ABCABCABC", Solution().decompressString("[3|ABC]"))
    }

    @Test
    fun LargerTests() {
        val expected =
            "VSJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKM" +
                    "YRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJ" +
                    "KMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKI" +
                    "SJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXU" +
                    "KISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKISJKMYRXUKICPYZHXOYPYZHXOYPYZHXOYPYZH" +
                    "XOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYP" +
                    "YZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHXOYPYZHX" +
                    "OYPYZHXOYODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODODO" +
                    "DODODODODODODODODODQLUFIGLUFIGLUFIGLUFIGLUFIGLUFIGLUFIGLUFIGLUFIGLUFIGLUFIGLUFIGLUFIGYVV" +
                    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVU" +
                    "UZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBK" +
                    "VUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHB" +
                    "BKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQM" +
                    "HBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZ" +
                    "QMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVUUZQMHBBKVU" +
                    "UZQMHBBKVUUZQMHBBMKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNU" +
                    "WZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNU" +
                    "WZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNU" +
                    "WZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZKDKQNUWZSEWIXEWIXEWIXEWIXEWIXE" +
                    "WIXEWIXEWIXEWIXEWIXEWIXTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTK" +
                    "JXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPG" +
                    "WTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWTKJ" +
                    "XPGWTKJXPGWTKJXPGWTKJXPGWTKJXPGWLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLM" +
                    "YADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJO" +
                    "LMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSS" +
                    "JOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOLMYADSSJOGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTA" +
                    "BGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVX" +
                    "RTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTABGVXRTAB" +
                    "GVXRTABGVXRTABGVXRTABGVXRTABGVXRTABJYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYXYX" +
                    "IQTLPNJYXIQTLPNJYXIQTLPNJYXIQTLPNJMFF"

        assertEquals(
            expected,
            Solution().decompressString("V[41|SJKMYRXUKI]C[30|PYZHXOY][49|OD]Q[13|LUFIG]Y[37|V][51|KVUUZQMHBB]M[39|KDKQNUWZ]S[11|EWIX][39|TKJXPGW][31|LMYADSSJO][36|GVXRTAB]J[25|YX][4|YXIQTLPNJ]M[2|F]")
        )
    }
}
